import pyautogui
import time
import os

os.system("start chrome")
time.sleep(2)

pyautogui.write("https://apps.mypurecloud.com/directory/#/analytics/?tabId=9ca2a47d-067f-42d2-9d3c-63d3d5edd024")
time.sleep(0.4)
pyautogui.press("enter")
pyautogui.hotkey("ctrl","t")

pyautogui.write("https://apps.mypurecloud.com/directory/#/engage/telephonyAdmin/metrics")
time.sleep(0.4)
pyautogui.press("enter")
pyautogui.hotkey("ctrl","t")

pyautogui.write("https://apps.mypurecloud.com/directory/#/engage/outbound/dashboards/outboundCampaigns")
time.sleep(0.4)
pyautogui.press("enter")
pyautogui.hotkey("ctrl","t")

pyautogui.write("https://brasilseg.workplace.com/chat/t/4835738449850954")
time.sleep(0.4)
pyautogui.press("enter")
pyautogui.hotkey("ctrl","t")

pyautogui.write("https://itsm-brasilseg.mapfre.com/smsgex/index.do")
pyautogui.press("enter")
time.sleep(3)
pyautogui.write('bandrezzo')
time.sleep(1.4)
pyautogui.press('tab')
time.sleep(1.4)
#pyautogui.write('password')
time.sleep(1)
pyautogui.press('enter')
pyautogui.hotkey("ctrl","t")

pyautogui.write("https://itsm-brasilseg.es.mapfre.net/smsgex/index.do")
pyautogui.press("enter")
time.sleep(2.5)
pyautogui.write('bandrezzo')
time.sleep(1)
pyautogui.press('tab')
time.sleep(1.5)
#pyautogui.write('password')
time.sleep(1)
pyautogui.press('enter')
pyautogui.hotkey("ctrl","t")

pyautogui.write("https://brasilseg.insight.khomp.com/")
time.sleep(0.4)
pyautogui.press("enter")
pyautogui.hotkey("ctrl","t")

pyautogui.write("https://mail.google.com/mail/u/0/?tab=rm&ogbl#inbox")
time.sleep(0.4)
pyautogui.press("enter")
pyautogui.hotkey("ctrl", "t")

pyautogui.write("https://app2.pontomais.com.br/registrar-ponto")
pyautogui.press('enter')

#pyautogui.hotkey("ctrl", "t")
#pyautogui.write("https://10.207.127.158/?error=Kerr3")
#time.sleep(0.5)
#pyautogui.press("enter")
#time.sleep(1.5)
#pyautogui.write("laguna")
#pyautogui.press("tab")
#pyautogui.write("valve2010!")
#pyautogui.press('enter')
#pyautogui.hotkey("ctrl", "t")
#pyautogui.write("http://10.207.127.155/?error=Kerr3")
#time.sleep(0.5)
#pyautogui.press('enter')
#time.sleep(1.5)
#pyautogui.write("laguna")
#pyautogui.press("tab")
#pyautogui.write("valve2010!")
#pyautogui.press('enter')